# Generated by Django 4.1.2 on 2022-10-31 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('body', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('GR', 'General'), ('SP', 'Sports'), ('GM', 'Gaming'), ('FD', 'Food')], default='GR', max_length=2)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('SM', 'Submitted'), ('RJ', 'Rejected'), ('AR', 'Archived')], default='DR', max_length=2)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
